name: Terraform EKS Setup

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from Git
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"

      # Verify Terraform version
      - name: Terraform version
        run: terraform --version

      # Initialize Terraform (no need to cd as we are already in Eks-terraform)
      - name: Terraform init
        run: terraform init

      # Validate Terraform files
      - name: Terraform validate
        run: terraform validate

      # Run Terraform plan
      - name: Terraform plan
        run: terraform plan

      # Apply or Destroy Terraform plan
      - name: Terraform apply/destroy
        run: terraform ${{ github.event.inputs.Action }} --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
